export { default as img1 } from './anh 1.jpg'
export { default as img2 } from './anh 2.jpg'
export { default as CrossBlue } from './cross-blue.svg'
export { default as CrossWhite } from './CrossWhite'
export { default as Hexagon } from './Hexagon'
export { default as IntersectImage } from './IntersectImage'
export { default as IntersectImageMobile } from './IntersectImageMobile'
